name: Auto Assign PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to user
        uses: kentaro-m/auto-assign-action@v1
        with:
          assignees: 'OrelNaranjoD'
          token: ${{ secrets.GITHUB_TOKEN }}
